### PR TITLE
feat: compose preview plugins

### PR DESCRIPTION
**Pull request by char0n**
#### NOTE1

SwaggerUI/SwaggerEditor@5 works on React@17 only. React@18 support is work in progress

#### NOTE2

`process` must be defined via `ProvidePlugin`. 

#### NOTE3

Preview plugins must be composed in a way as defined in https://github.com/swagger-api/swagger-editor/tree/next#using-preview-plugins-in-swaggerui

### CODE REVIEW

**Comment by pavelkornev** [comment]
@char0n thanks for the quick reaction. It seems to be working now.

Reg. **NOTE 3**: i copied over snippet from https://github.com/swagger-api/swagger-editor/tree/next#composing-with-swagger-ui-react — should the adapter be there as well?

**Comment by char0n** [comment]
The section you're referring to (https://github.com/swagger-api/swagger-editor/tree/next#composing-customized-swaggereditor-version) is part of [Composing customized SwaggerEditor version](https://github.com/swagger-api/swagger-editor/tree/next#composing-customized-swaggereditor-version). What you're looking for is [Using preview plugins in SwaggerUI](https://github.com/swagger-api/swagger-editor/tree/next#using-preview-plugins-in-swaggerui).

**Comment by pavelkornev** [comment]
@char0n, we have realized that Create-React-App is no longer supported by Facebook and due to some transitive deps security issues we need to move on something else.

I have tried Vite.js & Next.js. With Next.js there were lots of issues, but Vite.js looks promising, everything works out the box for the simple case (OpenAPI rendering). When I try to connect plugins for AsyncAPI rendering, I'm facing to WebAssembly (.wasm) issues.

Vite.js uses Rollup (comparing to Webpack in CRA). I have also added plugin to handle .wasm files, but it still doesn't work. Do you know what could be the issue with WebAssembly? I'm wondering why do we need WebAssembly to render AsyncAPI UI?

Here I created a very simplified snippet: https://github.com/pavelkornev/swagger-ui-react-app/tree/vite

To see the issues, you need to uncomment code in `./src/App.tsx` & `./vite.config.js`, then `npm run dev`.

I would really appreciate any hints where to look deeper in order to fix this.

**Comment by pavelkornev** [comment]
Screenshot 2023-10-31 at 13 53 19

**Comment by char0n** [comment]
@pavelkornev it's always just a question of configuratoon. 

Let's start by using SwaggerEditor@5 UMD bundle which has everything already prebuilt. When using UMD bundle, the only cons is that the resulting bundle size will be  quite large. But, it will work out of the box and will give us time to figure out the proper configuration.

```js
import SwaggerUI from 'swagger-ui';
import SwaggerUIStandalonePreset from 'swagger-ui/dist/swagger-ui-standalone-preset';
import SwaggerEditor from 'swagger-editor';
import 'swagger-editor/swagger-editor.css';

SwaggerUI({
  url: 'https://petstore.swagger.io/v2/swagger.json',
  dom_id: '#swagger-ui',
  presets: [SwaggerUI.presets.apis, SwaggerUIStandalonePreset],
  plugins: [
    SwaggerEditor.plugins.EditorContentType,
    SwaggerEditor.plugins.EditorPreviewAsyncAPI,
    SwaggerEditor.plugins.EditorPreviewAPIDesignSystems,
    SwaggerEditor.plugins.SwaggerUIAdapter,
    SwaggerUI.plugins.DownloadUrl,
  ],
});
```

**Pull request merged**
